CREATE TABLE maidens(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(50),
    surname VARCHAR(50),
    address VARCHAR(255),
    age INT(3),
    ethnicity VARCHAR(255),
    nationality VARCHAR(255),
    idNumber VARCHAR(15),
    weight DECIMAL,
    education VARCHAR(20),
    phoneNumber VARCHAR(15),
    complications VARCHAR(255),
    gaNumber DECIMAL,
    obsteric VARCHAR(15),
    childrenAlive INT(3),
    admissionDate DATETIME,
    deliveryDate DATETIME,
    deliveryMethod VARCHAR(50), 
    bloodLoss DECIMAL,
    placenta VARCHAR(40), 
    deliveredBy VARCHAR(255),
    assistedBy VARCHAR(255),
    regDate DATETIME,
    birthOutcome VARCHAR(12),
    sex VARCHAR(6),
    tetanus VARCHAR(20),
    childHIVStatus VARCHAR(20),
    apScore DECIMAL,
    labor INT,
    comments VARCHAR(255),
    birthPlace VARCHAR(255),
    profession varchar(255),
    vitaminA varchar(12)
    onAdmission varchar(20)
    afterAdmission VARCHAR(20),
    childWeight DECIMAL,
    hospitalNumber varchar(30),
    ancNumber varchar(30),
    
    );

-- CREATE TABLE maidens(
    name,
    surname,
    address,
    age ,
    ethnicity,
    nationality,
    idNumber,
    weight,
    education,
    phoneNumber,
    complications,
    gaNumber,
    obsteric,
    childrenAlive,
    admissionDate,
    deliveryDate,
    deliveryMethod, 
    bloodLoss,
    placenta, 
    deliveredBy,
    assistedBy,
    regDate,
    birthOutcome,
    sex,
    tetanus,
    childHIVStatus,
    apScore,
    labor,
    comments,
    birthPlace,
    profession,
    vitaminA,
    maidenHIVStatusBeforeAdmission,
    childWeight,
    maidenHIVStatusAfterAdmission,
    hospitalNumber,
    ancNumber
    
    );

      name=:name;
      surname=:surname,
      address=:address,
      age=:age,
      ethnicity=:ethnicity,
      nationality=:nationality,
      idNumber=:idNumber,
      weight=:weight,
      education=:education,
      phoneNumber=:phoneNumber,
      complications=:complications,
      gaNumber=:gaNumber,
      obsteric=:obsteric,
      childrenAlive=:childrenAlive,
      admissionDate=:admissionDate,
      deliveryDate=:deliveryDate,
      deliveryMethod=:deliveryMethod,
      bloodLoss=:bloodLoss,
      placenta=:placenta,
      deliveredBy=:deliveredBy,
      assistedBy=:assistedBy,
      regDate=:regDate,
      birthOutcome=:birthOutcome,
      sex=:sex,
      tetanus=:tetanus,
      childHIVStatus=:childHIVStatus,
      apScore=:apscore,
      labor=:labor,
      comments=:comments,
      birthPlace=:birthPlace,
      profession=:profession,
      vitaminA=:vitamins,
      onAdmission:=onAdmission,
      afterAdmission:=afterAdmission,
      childWeight:=childWeight,
      hosNum:=hosNum,
      ancNum:=ancNum,
      regBy:=regBy,
      twinStatus=:twinStatus





